# The theme used
theme = "apollo"
# TODO: understand what this line is doing
taxonomies = [{ name = "tags" }]

# The URL the site will be built for
base_url = "https://no-to-adhd.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


[extra]
# Put all your custom variables here
theme = "auto"
# toc = true
# mathjax = true
# mathjax_dollar_inline_enable = true

socials = [

]

menu = [
    { name = "/", url = "/", weight = 1 },
    { name = "/blogs", url = "/blog", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
